/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 12 22:22:41 GMT 2023
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.Functions;
import org.example.Utravel;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Functions_ESTest extends Functions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doDeleteCommand("flight", (String) null, utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not Found
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doPostCommand("tickets", "v9':I#VK]0lqIdi", utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doPostCommand("login", "%`:>,R*3.b", utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.signup("b?&:Yi,,WjkkS;{E", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = Functions.splitFirstSign("b?&:Yi,,WjkkS;{E");
      assertEquals(":Yi,,WjkkS;{E", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.wallet("", utravel0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.wallet((String) null, utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.splitFirstSign((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.signup((String) null, (Utravel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.showTickets((String) null, utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.showFlights("v", (Utravel) null);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.readNameAndPass((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.readId("");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.readId((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.login("b?&:Yi,,WjkkS;{E", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.login((String) null, utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doPostCommand((String) null, "economy", utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doGetCommands((String) null, "K#&&Y!]'$$Zp#Z", utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doDeleteCommand((String) null, "M-QyKhtY7'x8 P", utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doCommand((String) null, utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doCommand("", utravel0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.cancelTicket("", utravel0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.cancelTicket((String) null, utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.buyTicket("", utravel0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.buyTicket((String) null, utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.applyFilter("", utravel0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.applyFilter((String) null, utravel0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.readId("b?&:Yi,,WjkkS;{E");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.splitFirstSign("`92h4o}htC=Gq");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.splitFirstSign("V?");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.login("", utravel0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.doCommand("i,1wtQoExM[ LD)?r'", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doDeleteCommand("tickets", "tickets", utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doDeleteCommand("filters", "filters", utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Permission Denied
         //
         verifyException("org.example.Utravel", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doPostCommand("ticDket", "vD':I#VK]0lqIdi", utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not Found
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doPostCommand("logout", "GET", utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Permission Denied
         //
         verifyException("org.example.Utravel", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doPostCommand("filters", "k", utravel0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doGetCommands("flights", "flights", utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.doGetCommands(">\"PL.q=/p", "\n", utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not Found
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.applyFilter("b?&:Yi,,WjkkS;{E", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.applyFilter("b?&:Yi,,Wjkk ;{E", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.showTickets("", utravel0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Permission Denied
         //
         verifyException("org.example.Utravel", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.showTickets("0", utravel0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.buyTicket("b?&:Yi,,WjkkS;E", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.showFlights("", (Utravel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.showFlights("b?&:Yi,,WjkkS;{E", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.wallet("b?&:Yi,,Wjkk ;{E", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.wallet("b?&:Yi,,WjkkS;{E", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.readNameAndPass("Bd Request N\n");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Functions functions0 = new Functions();
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Utravel utravel0 = new Utravel();
      // Undeclared exception!
      try { 
        Functions.signup("", utravel0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.cancelTicket("b?&:Yi,,WjkkS;{E", (Utravel) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Bad Request
         //
         verifyException("org.example.Functions", e);
      }
  }
}
